### ISSUE TITLE
TagBot?

### ISSUE THREAD

**Issue by timholy** [HolyLab/HolyLabRegistry#143]
https://discourse.julialang.org/t/ann-required-updates-to-tagbot-yml/49249 suggests we can set up tagbot on this registry. It would save having to manually add tags when registering new versions.

**Comment by timholy** [comment]
So, it looks like you can get nice tagging if you run the TagBot workflow manually:
- https://github.com/HolyLab/RegisterQD.jl/actions/workflows/TagBot.yml
- https://github.com/HolyLab/RegisterQD.jl/releases/tag/v0.2.5 (sweet!)

So I guess the challenge would be to figure out how to trigger it from HolyLabRegistry.

**Comment by IanButterworth** [comment]
We've set this up for another registry. I can pull together the actions .yml files

**Comment by timholy** [comment]
The TagBot actions files are there, e.g., https://github.com/HolyLab/RegisterDeformation.jl/blob/master/.github/workflows/TagBot.yml (and many others). We just don't seem to have any kind of automatic trigger working.

**Comment by IanButterworth** [comment]
What we have is a bit more than just tagbot. 

We have it set up so that when a commit to master is made that includes a new version in the Project.toml, the repo action triggers an action on the registry to register the new version at that commit. Then that triggers tagbot back on the original repo to create a new GitHub tag/release. 

That full process may be a bit to limiting to which commit to make a release on (sometimes you don't want the release on the commit where the Project.toml version is actually changed).

But the latter part can be used here. TagBot can be triggered by the registry when a new version is added.

**Comment by IanButterworth** [comment]
Here's the registry action https://github.com/HolyLab/HolyLabRegistry/pull/161

All the tagbots will need to be updated to work with that

**Comment by timholy** [comment]
Fixed by #161 (thanks @IanButterworth !)
